### ISSUE TITLE
在小游戏项目中 import 报错

### ISSUE THREAD

**Issue by littlee** [wujjpp/socket.io.xcx#1]
```
gameThirdScriptError
Cannot use 'in' operator to search for 'WebkitAppearance' in undefined
TypeError: Cannot use 'in' operator to search for 'WebkitAppearance' in undefined
    at Function.useColors (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:993:85)
    at createDebug (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:1045:107)
    at Object.<anonymous> (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:565:72)
    at Object.r.12.debug (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:588:10)
    at s (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:27:49)
    at http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:28:37
    at Object.r.8.../../socket.io-parser (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:329:17)
    at s (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:27:49)
    at e (http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:32:7)
    at http://127.0.0.1:55020/game/js/libs/socket.io.xcx.min.js:34:4
```

**Comment by 0x2CA** [comment]
我使用是正常的
```ts
import io = require("./Libs/js/socket.io.xcx.min");
```

**Comment by littlee** [comment]
👌
